name: Staging CI - Development

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set environment variables
      env:
          APP_PORT: ${{ secrets.DEV_APP_PORT }}
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          DATABASE_URI: ${{ secrets.DEV_DATABASE_URI }} 
          PAYSTACK_SK: ${{ secrets.DEV_PAYSTACK_SK }}   
          EMAIL_KEY: ${{ secrets.EMAIL_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          TREBLLE_API_KEY: ${{ secrets.DEV_TREBLLE_API_KEY }}   
          TREBLLE_PROJECT_ID: ${{ secrets.DEV_TREBLLE_PROJECT_ID }} 
          REDIS_PORT: ${{ secrets.DEV_REDIS_PORT }}     
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_HOST: ${{ secrets.DEV_REDIS_HOST }}     

      run: |
          touch .env.development
          echo "APP_PORT=${APP_PORT}" >> .env.development
          echo "JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}" >> .env.development
          echo "JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}" >> .env.development
          echo "PASSWORD_HASH=${PASSWORD_HASH}" >> .env.development
          echo "PASSWORD_SALT=${PASSWORD_SALT}" >> .env.development
          echo "DATABASE_URI=${DATABASE_URI}" >> .env.development
          echo "PAYSTACK_SK=${PAYSTACK_SK}" >> .env.development
          echo "EMAIL_KEY=${EMAIL_KEY}" >> .env.development
          echo "EMAIL_SENDER=${EMAIL_SENDER}" >> .env.development
          echo "TREBLLE_PROJECT_ID=${TREBLLE_PROJECT_ID}" >> .env.development
          echo "TREBLLE_API_KEY=${TREBLLE_API_KEY}" >> .env.development
          echo "REDIS_PORT=${REDIS_PORT}" >> .env.development
          echo "REDIS_USER=${REDIS_USER}" >> .env.development
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env.development
          echo "REDIS_HOST=${REDIS_HOST}" >> .env.development

    - run: npm install
    - run: npm run staging-ci
    - run: pm2 restart staging
