name: Deploy staging

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed

  push:
    branches:
    - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run ci-test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}