name: Deploy to Railway after Workflow 1

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed
  push:
    branches:
    - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install packages
        run: npm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run ci-test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}