name: Staging CI

on:
  push:
    branches:
     - development

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Set environment variables
      env:
          APP_PORT: ${{ secrets.APP_PORT }}
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          PAYSTACK_SK: ${{secrets.PAYSTACK_SK}}
          EMAIL_KEY: ${{secrets.EMAIL_KEY}}
          EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}

      run: |
          touch .env
          echo "APP_PORT=${APP_PORT}" >> .env
          echo "JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}" >> .env
          echo "JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}" >> .env
          echo "PASSWORD_HASH=${PASSWORD_HASH}" >> .env
          echo "PASSWORD_SALT=${PASSWORD_SALT}" >> .env
          echo "DATABASE_URI=${DATABASE_URI}" >> .env
          echo "PAYSTACK_SK=${PAYSTACK_SK}" >> .env
          echo "EMAIL_KEY=${EMAIL_KEY}" >> .env
          echo "EMAIL_SENDER=${EMAIL_SENDER}" >> .env

    - run: npm install
    - run: npm run staging-ci
    - run: pm2 restart staging
