name: Testing

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set environment variables
        env:
          APP_PORT: ${{ secrets.DEV_APP_PORT }}
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.DEV_JWT_REFRESH_TOKEN_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.DEV_JWT_TOKEN_SECRET }}
          PASSWORD_HASH: ${{ secrets.DEV_PASSWORD_HASH }}
          PASSWORD_SALT: ${{ secrets.DEV_PASSWORD_SALT }}
          DATABASE_URI: ${{ secrets.DEV_DATABASE_URI }}
          PAYSTACK_SK: ${{ secrets.DEV_PAYSTACK_SK }}
          EMAIL_KEY: ${{ secrets.DEV_EMAIL_KEY }}
          EMAIL_SENDER: ${{ secrets.DEV_EMAIL_SENDER }}
          TREBLLE_API_KEY: ${{ secrets.DEV_TREBLLE_API_KEY }}
          TREBLLE_PROJECT_ID: ${{ secrets.DEV_TREBLLE_PROJECT_ID }}
          REDIS_PORT: ${{ secrets.DEV_REDIS_PORT }}
          REDIS_USER: ${{ secrets.DEV_REDIS_USER }}
          REDIS_PASSWORD: ${{ secrets.DEV_REDIS_PASSWORD }}
          REDIS_HOST: ${{ secrets.DEV_REDIS_HOST }}

        run: |
          echo "APP_PORT=${APP_PORT}"
          echo "JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}"
          echo "JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}"
          echo "PASSWORD_HASH=${PASSWORD_HASH}"
          echo "PASSWORD_SALT=${PASSWORD_SALT}"
          echo "DATABASE_URI=${DATABASE_URI}"
          echo "PAYSTACK_SK=${PAYSTACK_SK}"
          echo "EMAIL_KEY=${EMAIL_KEY}"
          echo "EMAIL_SENDER=${EMAIL_SENDER}"
          echo "TREBLLE_PROJECT_ID=${TREBLLE_PROJECT_ID}"
          echo "TREBLLE_API_KEY=${TREBLLE_API_KEY}"
          echo "REDIS_PORT=${REDIS_PORT}"
          echo "REDIS_USER=${REDIS_USER}"
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}"
          echo "REDIS_HOST=${REDIS_HOST}"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run build
          npm run test
