name: Testing

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set environment variables
        env:
          PORT: ${{ secrets.PORT }}
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          PAYSTACK_SK: ${{ secrets.PAYSTACK_SK }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}

        run: |
          echo "PORT=${PORT}" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}" >> $GITHUB_ENV
          echo "JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}" >> $GITHUB_ENV
          echo "PASSWORD_HASH=${PASSWORD_HASH}" >> $GITHUB_ENV
          echo "PASSWORD_SALT=${PASSWORD_SALT}" >> $GITHUB_ENV
          echo "DATABASE_URI=${DATABASE_URI}" >> $GITHUB_ENV
          echo "PAYSTACK_SK=${PAYSTACK_SK}" >> $GITHUB_ENV
          echo "REDIS_PORT=${REDIS_PORT}" >> $GITHUB_ENV
          echo "REDIS_USER=${REDIS_USER}" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> $GITHUB_ENV
          echo "REDIS_HOST=${REDIS_HOST}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run build
          npm run test
